version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: ticketmind_postgres
    restart: always
    environment:
      POSTGRES_USER: ticketmind        # HEPSİ AYNI
      POSTGRES_PASSWORD: ticketmind    # HEPSİ AYNI
      POSTGRES_DB: ticketmind          # HEPSİ AYNI
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: